"""Professional PDF security assessment reports built with ReportLab.

Produces a branded, paginated document with tables, severity indicators,
headers/footers and properly wrapped long text.
"""

import logging
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger("nexcyr.pdf")

PAGE_WIDTH, PAGE_HEIGHT = A4

# NexCYR brand palette
BRAND_DARK = colors.HexColor("#0B1220")
BRAND_PANEL = colors.HexColor("#121B2E")
BRAND_CYAN = colors.HexColor("#00D4FF")
BRAND_BLUE = colors.HexColor("#3B82F6")
BRAND_VIOLET = colors.HexColor("#8B5CF6")
TEXT_LIGHT = colors.HexColor("#E6EDF7")
TEXT_MUTED = colors.HexColor("#9FB0C8")

SEVERITY_COLORS = {
    "critical": colors.HexColor("#FF3B5C"),
    "high": colors.HexColor("#FF8A3D"),
    "medium": colors.HexColor("#FFD166"),
    "low": colors.HexColor("#4ADE80"),
    "info": colors.HexColor("#38BDF8"),
}

REPORT_FILENAME = "NexCYR_Security_Assessment_Report.pdf"


def _styles():
    base = getSampleStyleSheet()
    styles = {
        "cover_title": ParagraphStyle(
            "cover_title", parent=base["Title"], fontName="Helvetica-Bold",
            fontSize=34, textColor=BRAND_CYAN, alignment=TA_CENTER, spaceAfter=6,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub", parent=base["Normal"], fontName="Helvetica",
            fontSize=13, textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=4,
        ),
        "h1": ParagraphStyle(
            "h1", parent=base["Heading1"], fontName="Helvetica-Bold",
            fontSize=16, textColor=colors.HexColor("#0EA5E9"),
            spaceBefore=14, spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontName="Helvetica-Bold",
            fontSize=12.5, textColor=BRAND_DARK, spaceBefore=10, spaceAfter=5,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"], fontName="Helvetica",
            fontSize=9.8, leading=14, alignment=TA_JUSTIFY, spaceAfter=6,
            textColor=colors.HexColor("#1F2937"),
        ),
        "small": ParagraphStyle(
            "small", parent=base["Normal"], fontName="Helvetica",
            fontSize=8.2, leading=11, textColor=TEXT_MUTED,
        ),
        "cell": ParagraphStyle(
            "cell", parent=base["Normal"], fontName="Helvetica",
            fontSize=8.4, leading=11, textColor=colors.HexColor("#1F2937"),
        ),
        "cell_head": ParagraphStyle(
            "cell_head", parent=base["Normal"], fontName="Helvetica-Bold",
            fontSize=8.6, leading=11, textColor=colors.white,
        ),
    }
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, PAGE_HEIGHT - 16 * mm, PAGE_WIDTH, 16 * mm, stroke=0, fill=1)
    canvas.setFillColor(BRAND_CYAN)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(18 * mm, PAGE_HEIGHT - 10.5 * mm, "NexCYR")
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(38 * mm, PAGE_HEIGHT - 10.5 * mm, "Security Assessment Report")
    canvas.drawRightString(
        PAGE_WIDTH - 18 * mm, PAGE_HEIGHT - 10.5 * mm, "CONFIDENTIAL"
    )
    # Footer
    canvas.setStrokeColor(colors.HexColor("#D5DEEA"))
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 14 * mm, PAGE_WIDTH - 18 * mm, 14 * mm)
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(18 * mm, 10 * mm, "Generated by NexCYR — AI-Powered Cybersecurity Platform")
    canvas.drawRightString(PAGE_WIDTH - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _cover_page(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, stroke=0, fill=1)

    # Subtle grid
    canvas.setStrokeColor(colors.HexColor("#16233C"))
    canvas.setLineWidth(0.4)
    for x in range(0, int(PAGE_WIDTH), 18):
        canvas.line(x, 0, x, PAGE_HEIGHT)
    for y in range(0, int(PAGE_HEIGHT), 18):
        canvas.line(0, y, PAGE_WIDTH, y)

    # Brand mark: hexagon core with orbit rings
    cx, cy = PAGE_WIDTH / 2, PAGE_HEIGHT - 95 * mm
    canvas.setStrokeColor(BRAND_CYAN)
    canvas.setLineWidth(1.6)
    canvas.circle(cx, cy, 30 * mm, stroke=1, fill=0)
    canvas.setStrokeColor(BRAND_VIOLET)
    canvas.setLineWidth(0.9)
    canvas.circle(cx, cy, 38 * mm, stroke=1, fill=0)
    canvas.setStrokeColor(BRAND_BLUE)
    canvas.circle(cx, cy, 22 * mm, stroke=1, fill=0)
    canvas.setFillColor(BRAND_CYAN)
    canvas.setFont("Helvetica-Bold", 26)
    canvas.drawCentredString(cx, cy - 9, "N")

    canvas.setFillColor(BRAND_CYAN)
    canvas.setFont("Helvetica-Bold", 40)
    canvas.drawCentredString(cx, cy - 62 * mm, "NexCYR")
    canvas.setFillColor(TEXT_LIGHT)
    canvas.setFont("Helvetica", 13)
    canvas.drawCentredString(
        cx, cy - 74 * mm, "AI-POWERED UNIFIED CYBERSECURITY ASSESSMENT & PURPLE TEAM PLATFORM"
    )

    canvas.setStrokeColor(BRAND_CYAN)
    canvas.setLineWidth(1)
    canvas.line(cx - 60 * mm, cy - 84 * mm, cx + 60 * mm, cy - 84 * mm)

    canvas.setFillColor(colors.HexColor("#FF3B5C"))
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawCentredString(cx, cy - 96 * mm, "CONFIDENTIAL — AUTHORIZED RECIPIENTS ONLY")
    canvas.restoreState()


def _severity_cell(severity, styles):
    color = SEVERITY_COLORS.get((severity or "info").lower(), TEXT_MUTED)
    para = Paragraph(f'<font color="{color.hexval()}"><b>{(severity or "info").upper()}</b></font>', styles["cell"])
    return para


def _table(header, rows, col_widths, styles, severity_col=None):
    data = [[Paragraph(h, styles["cell_head"]) for h in header]]
    for row in rows:
        cells = []
        for idx, cell in enumerate(row):
            if severity_col is not None and idx == severity_col:
                cells.append(_severity_cell(str(cell), styles))
            else:
                cells.append(Paragraph(str(cell) if cell is not None else "", styles["cell"]))
        data.append(cells)

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), BRAND_DARK),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F6FC")]),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#C9D6E8")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _section(story, title, styles):
    story.append(Paragraph(title, styles["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_CYAN, spaceAfter=8))


def _empty_note(story, text, styles):
    story.append(Paragraph(f"<i>{text}</i>", styles["body"]))


def generate_assessment_pdf(data: dict, output_dir: Path) -> Path:
    """Build the full PDF from aggregated report data and return its path."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / REPORT_FILENAME

    styles = _styles()
    content_width = PAGE_WIDTH - 36 * mm

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=22 * mm,
        bottomMargin=20 * mm,
        title="NexCYR Security Assessment Report",
        author="NexCYR",
    )

    story = []
    assessment = data.get("assessment")
    risk = data.get("risk", {})
    generated = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    # ---------- COVER (drawn on canvas) + cover text block ----------
    story.append(Spacer(1, PAGE_HEIGHT - 200 * mm))
    cover_rows = [
        ["Assessment", assessment["name"] if assessment else "Platform-wide (all assessments)"],
        ["Assessment ID", str(assessment["id"]) if assessment else "—"],
        ["Generated", generated],
        ["Classification", "Confidential"],
        ["Overall Risk", f'{str(risk.get("level", "unknown")).upper()} (score {risk.get("score", 0)}/100)'],
    ]
    cover_table = Table(
        [[Paragraph(k, styles["cell_head"]), Paragraph(v, styles["cell"])] for k, v in cover_rows],
        colWidths=[45 * mm, content_width - 45 * mm],
    )
    cover_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), BRAND_PANEL),
                ("BACKGROUND", (1, 0), (1, -1), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, BRAND_CYAN),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(cover_table)
    story.append(PageBreak())

    # ---------- 1. EXECUTIVE SUMMARY ----------
    _section(story, "1. Executive Summary", styles)
    dist = risk.get("severity_distribution", {})
    summary_text = (
        f'This report presents the results of the NexCYR security assessment'
        f'{" for <b>" + assessment["name"] + "</b>" if assessment else " across all recorded assessments"}. '
        f'A total of <b>{risk.get("total_findings", 0)}</b> finding(s) were recorded, of which '
        f'<b>{dist.get("critical", 0)}</b> are critical, <b>{dist.get("high", 0)}</b> high, '
        f'<b>{dist.get("medium", 0)}</b> medium, <b>{dist.get("low", 0)}</b> low and '
        f'<b>{dist.get("info", 0)}</b> informational. '
        f'<b>{risk.get("open_findings", 0)}</b> finding(s) remain open. '
        f'The overall risk level is <b>{str(risk.get("level", "unknown")).upper()}</b> '
        f'with a risk score of <b>{risk.get("score", 0)}/100</b>.'
    )
    if risk.get("total_findings", 0) == 0:
        summary_text += (
            " No security findings or activity are recorded in the platform for this scope; "
            "the risk values above therefore reflect an absence of recorded data, not a verified clean posture."
        )
    story.append(Paragraph(summary_text, styles["body"]))

    # ---------- 2. SCOPE ----------
    _section(story, "2. Scope", styles)
    targets = data.get("targets", [])
    if targets:
        story.append(
            _table(
                ["ID", "Name", "Value", "Type", "Authorized", "Status"],
                [
                    [t["id"], t["name"] or "—", t["value"], t["target_type"],
                     "Yes" if t["authorized"] else "No", t["status"]]
                    for t in targets
                ],
                [12 * mm, 38 * mm, 52 * mm, 20 * mm, 22 * mm, content_width - 144 * mm],
                styles,
            )
        )
    else:
        _empty_note(story, "No targets are recorded for this scope.", styles)
    story.append(Spacer(1, 4))
    story.append(
        Paragraph(
            "All scanning and reconnaissance activity in NexCYR requires an explicitly "
            "authorized target record. Unauthorized targets are excluded from active testing.",
            styles["body"],
        )
    )

    # ---------- 3. METHODOLOGY ----------
    _section(story, "3. Methodology", styles)
    story.append(
        Paragraph(
            "The assessment followed the NexCYR unified methodology: (1) scope definition and "
            "authorization capture; (2) safe reconnaissance — host discovery, port discovery and "
            "service enumeration on authorized targets only; (3) vulnerability analysis of observed "
            "services with rule-based risk scoring; (4) SOC event monitoring and correlation; "
            "(5) purple team validation of detections; and (6) reporting with prioritized "
            "remediation guidance. No destructive exploitation was performed at any stage.",
            styles["body"],
        )
    )

    # ---------- 4. RISK OVERVIEW ----------
    _section(story, "4. Risk Overview", styles)
    story.append(Paragraph(f'Overall risk score: <b>{risk.get("score", 0)} / 100</b> — level <b>{str(risk.get("level", "unknown")).upper()}</b>', styles["body"]))
    story.append(
        _table(
            ["Severity", "Count"],
            [[sev.upper(), dist.get(sev, 0)] for sev in ["critical", "high", "medium", "low", "info"]],
            [content_width * 0.5, content_width * 0.5],
            styles,
            severity_col=0,
        )
    )

    # ---------- 5. SCAN SUMMARY ----------
    _section(story, "5. Scan Summary", styles)
    scans = data.get("scans", [])
    if scans:
        def _source(s):
            src = (s.get("execution_source") or "CLOUD").upper()
            agent = s.get("agent_name") or ""
            ver = s.get("agent_version") or ""
            if src == "AGENT" and agent:
                return f"AGENT · {agent}" + (f" (v{ver})" if ver else "")
            return "CLOUD · Cloud Scanner"

        story.append(
            _table(
                ["ID", "Target", "Type", "Source", "Status", "Completed", "Summary"],
                [
                    [s["id"], s["target"], s["scan_type"], _source(s), s["status"],
                     (s["completed_at"] or "—")[:19].replace("T", " "), s["summary"] or "—"]
                    for s in scans
                ],
                [10 * mm, 30 * mm, 20 * mm, 34 * mm, 20 * mm, 30 * mm, content_width - 144 * mm],
                styles,
            )
        )
    else:
        _empty_note(story, "No scans are recorded for this scope.", styles)

    # ---------- 6. FINDINGS SUMMARY ----------
    _section(story, "6. Findings Summary", styles)
    findings = data.get("findings", [])
    if findings:
        story.append(
            _table(
                ["ID", "Title", "Severity", "Score", "Status"],
                [[f["id"], f["title"], f["severity"], f["risk_score"], f["status"]] for f in findings],
                [12 * mm, content_width - 82 * mm, 24 * mm, 16 * mm, 30 * mm],
                styles,
                severity_col=2,
            )
        )
    else:
        _empty_note(story, "No findings are recorded for this scope.", styles)

    # ---------- 7. DETAILED FINDINGS ----------
    _section(story, "7. Detailed Findings", styles)
    if findings:
        for f in findings:
            story.append(
                Paragraph(f'7.{findings.index(f) + 1}  {f["title"]}  [{f["severity"].upper()} — score {f["risk_score"]}]', styles["h2"])
            )
            detail_rows = [
                ["Status", f["status"]],
                ["Affected target", f["target"] or "—"],
                ["Recorded", (f["created_at"] or "—")[:19].replace("T", " ")],
                ["Description", f["description"] or "No description recorded."],
                ["Evidence", f["evidence"] or "No evidence recorded."],
                ["Remediation", f["remediation"] or "No remediation recorded."],
            ]
            detail_table = Table(
                [[Paragraph(k, styles["cell_head"]), Paragraph(v, styles["cell"])] for k, v in detail_rows],
                colWidths=[32 * mm, content_width - 32 * mm],
            )
            detail_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (0, -1), BRAND_PANEL),
                        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#C9D6E8")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(detail_table)
            story.append(Spacer(1, 8))
    else:
        _empty_note(story, "No findings to detail for this scope.", styles)

    # ---------- 8. SOC MONITORING SUMMARY ----------
    _section(story, "8. SOC Monitoring Summary", styles)
    events = data.get("soc_events", [])
    if events:
        story.append(
            _table(
                ["ID", "Type", "Source", "Severity", "Status", "Message"],
                [
                    [e["id"], e["event_type"], e["source"], e["severity"], e["status"], e["message"]]
                    for e in events[:40]
                ],
                [12 * mm, 28 * mm, 24 * mm, 20 * mm, 18 * mm, content_width - 102 * mm],
                styles,
                severity_col=3,
            )
        )
    else:
        _empty_note(story, "No SOC events are recorded for this scope.", styles)

    # ---------- 9. EVENT CORRELATION SUMMARY ----------
    _section(story, "9. Event Correlation Summary", styles)
    correlation = data.get("correlation", {})
    clusters = correlation.get("clusters", [])
    if clusters:
        story.append(
            _table(
                ["Category", "Events", "Max Severity", "Open", "Window", "Assessment"],
                [
                    [
                        c["category"].replace("_", " ").title(),
                        c["event_count"],
                        c["max_severity"].upper(),
                        c["open_count"],
                        f'{(c["first_seen"] or "")[:10]} → {(c["last_seen"] or "")[:10]}',
                        c["assessment"],
                    ]
                    for c in clusters[:15]
                ],
                [30 * mm, 14 * mm, 22 * mm, 12 * mm, 30 * mm, content_width - 108 * mm],
                styles,
                severity_col=2,
            )
        )
    else:
        _empty_note(
            story,
            correlation.get("note", "No correlated event activity recorded."),
            styles,
        )

    # ---------- 10. PURPLE TEAM VALIDATION ----------
    _section(story, "10. Purple Team Validation", styles)
    tests = data.get("purple_team_tests", [])
    if tests:
        story.append(
            _table(
                ["ID", "Test", "Technique", "Status", "Detection"],
                [[t["id"], t["name"], t["technique"] or "—", t["status"], t["detection_status"]] for t in tests],
                [12 * mm, 55 * mm, 45 * mm, 25 * mm, content_width - 137 * mm],
                styles,
            )
        )
    else:
        _empty_note(story, "No purple team tests are recorded for this scope.", styles)

    # ---------- 11. WI-FI SECURITY ----------
    _section(story, "11. Wi-Fi Security", styles)
    wifi = data.get("wifi_assessments", [])
    if wifi:
        story.append(
            _table(
                ["ID", "SSID", "Security", "Channel", "Status", "Assessment"],
                [[w["id"], w["ssid"], w["security_type"] or "—", w["channel"] or "—", w["status"], w["assessment"] or "—"] for w in wifi],
                [12 * mm, 38 * mm, 24 * mm, 18 * mm, 22 * mm, content_width - 114 * mm],
                styles,
            )
        )
    else:
        _empty_note(story, "No Wi-Fi assessments are recorded.", styles)

    # ---------- 12. NEXCYR INTELLIGENCE SUMMARY ----------
    _section(story, "12. NexCYR Intelligence Summary", styles)
    intelligence = data.get("intelligence_summaries", [])
    if intelligence:
        story.append(
            Paragraph(
                "Recent contextual analyses produced by NexCYR Intelligence "
                "from live platform data:",
                styles["body"],
            )
        )
        for item in intelligence:
            story.append(
                Paragraph(
                    f'<b>Q:</b> {item["question"] or "—"}  <font size="7">[{item["provider"]}]</font>',
                    styles["body"],
                )
            )
            story.append(Paragraph(f'<b>A:</b> {item["summary"] or "—"}', styles["body"]))
    else:
        _empty_note(story, "No NexCYR Intelligence analyses recorded yet.", styles)

    # ---------- 13. RECOMMENDATIONS ----------
    _section(story, "13. Recommendations", styles)
    recommendations = []
    open_critical = [f for f in findings if f["severity"] in ("critical", "high") and f["status"] == "open"]
    if open_critical:
        recommendations.append(
            f"Prioritize remediation of {len(open_critical)} open critical/high finding(s), starting with the highest risk score."
        )
    for f in findings[:10]:
        if f["remediation"]:
            recommendations.append(f'{f["title"]}: {f["remediation"]}')
    unauthorized = [t for t in targets if not t["authorized"]]
    if unauthorized:
        recommendations.append(
            f"Obtain and record formal authorization for {len(unauthorized)} target(s) before any further testing."
        )
    missed = [t for t in tests if t["detection_status"] == "missed"]
    if missed:
        recommendations.append(
            f"Improve detection coverage for {len(missed)} purple team test(s) that were not detected."
        )
    if not recommendations:
        recommendations.append(
            "No open high-risk items are recorded. Maintain continuous monitoring, re-run authorized scans periodically and keep detection validation current."
        )
    for idx, rec in enumerate(recommendations, 1):
        story.append(Paragraph(f"{idx}. {rec}", styles["body"]))

    # ---------- 14. CONCLUSION ----------
    _section(story, "14. Conclusion", styles)
    story.append(
        Paragraph(
            f'The recorded risk level for this scope is <b>{str(risk.get("level", "unknown")).upper()}</b> '
            f'(score {risk.get("score", 0)}/100) based on {risk.get("total_findings", 0)} recorded finding(s). '
            "All values in this report are derived exclusively from data stored in the NexCYR platform; "
            "no results were fabricated or extrapolated. Remediation progress should be validated by "
            "re-scanning authorized targets and re-running purple team detection validation.",
            styles["body"],
        )
    )
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"Report generated {generated} by NexCYR v1.0.0.", styles["small"]))

    def on_first_page(canvas, doc_):
        _cover_page(canvas, doc_)

    def on_later_pages(canvas, doc_):
        _header_footer(canvas, doc_)

    logger.info("Generating PDF report at %s", output_path)
    doc.build(story, onFirstPage=on_first_page, onLaterPages=on_later_pages)
    return output_path
